[2025-04-13T06:59:21.183+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T06:59:18.678161+00:00 [queued]>
[2025-04-13T06:59:21.262+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T06:59:18.678161+00:00 [queued]>
[2025-04-13T06:59:21.263+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-04-13T06:59:21.264+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-04-13T06:59:21.264+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-04-13T06:59:21.295+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_from_postgresql> on 2025-04-13 06:59:18.678161+00:00
[2025-04-13T06:59:21.305+0000] {standard_task_runner.py:52} INFO - Started process 418 to run task
[2025-04-13T06:59:21.312+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'M3_GA_pipeline', 'fetch_from_postgresql', 'manual__2025-04-13T06:59:18.678161+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_galuh_alifani_DAG.py', '--cfg-path', '/tmp/tmp9hp_nflb', '--error-file', '/tmp/tmpfb9kyj4g']
[2025-04-13T06:59:21.316+0000] {standard_task_runner.py:80} INFO - Job 21: Subtask fetch_from_postgresql
[2025-04-13T06:59:21.584+0000] {task_command.py:371} INFO - Running <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T06:59:18.678161+00:00 [running]> on host a0a67293f3f1
[2025-04-13T06:59:21.922+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Galuh
AIRFLOW_CTX_DAG_ID=M3_GA_pipeline
AIRFLOW_CTX_TASK_ID=fetch_from_postgresql
AIRFLOW_CTX_EXECUTION_DATE=2025-04-13T06:59:18.678161+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-13T06:59:18.678161+00:00
[2025-04-13T06:59:21.924+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_galuh_alifani_DAG.py", line 47, in load_data
    conn=db.connect(conn_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5434 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-13T06:59:21.968+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=M3_GA_pipeline, task_id=fetch_from_postgresql, execution_date=20250413T065918, start_date=20250413T065921, end_date=20250413T065921
[2025-04-13T06:59:22.002+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task fetch_from_postgresql (connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5434 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 418)
[2025-04-13T06:59:22.047+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-04-13T06:59:22.182+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
