[2025-04-13T07:01:42.381+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T07:01:40.229305+00:00 [queued]>
[2025-04-13T07:01:42.393+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T07:01:40.229305+00:00 [queued]>
[2025-04-13T07:01:42.393+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-04-13T07:01:42.394+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-04-13T07:01:42.394+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-04-13T07:01:42.411+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_from_postgresql> on 2025-04-13 07:01:40.229305+00:00
[2025-04-13T07:01:42.416+0000] {standard_task_runner.py:52} INFO - Started process 487 to run task
[2025-04-13T07:01:42.419+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'M3_GA_pipeline', 'fetch_from_postgresql', 'manual__2025-04-13T07:01:40.229305+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_galuh_alifani_DAG.py', '--cfg-path', '/tmp/tmp0ydsdnng', '--error-file', '/tmp/tmppl_z0cbi']
[2025-04-13T07:01:42.420+0000] {standard_task_runner.py:80} INFO - Job 22: Subtask fetch_from_postgresql
[2025-04-13T07:01:42.551+0000] {task_command.py:371} INFO - Running <TaskInstance: M3_GA_pipeline.fetch_from_postgresql manual__2025-04-13T07:01:40.229305+00:00 [running]> on host a0a67293f3f1
[2025-04-13T07:01:42.673+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Galuh
AIRFLOW_CTX_DAG_ID=M3_GA_pipeline
AIRFLOW_CTX_TASK_ID=fetch_from_postgresql
AIRFLOW_CTX_EXECUTION_DATE=2025-04-13T07:01:40.229305+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-13T07:01:40.229305+00:00
[2025-04-13T07:01:42.675+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_galuh_alifani_DAG.py", line 47, in load_data
    conn=db.connect(conn_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (192.168.0.4), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-13T07:01:42.702+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=M3_GA_pipeline, task_id=fetch_from_postgresql, execution_date=20250413T070140, start_date=20250413T070142, end_date=20250413T070142
[2025-04-13T07:01:42.719+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task fetch_from_postgresql (connection to server at "postgres" (192.168.0.4), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 487)
[2025-04-13T07:01:42.752+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-04-13T07:01:42.822+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
